apiVersion: v1
kind: Service
metadata:
  name: chat-api
  namespace: default
  labels:
    app: chat-api
spec:
  ports:
    - port: 5006
  selector:
    app: chat-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: chat-api
  name: chat-api
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chat-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chat-api
    spec:
      containers:
      - env:
        - name: POSTGRES_CONNECTION_URI
          value: "postgres://postgres:password@postgres:5432/chat"
        image: us.gcr.io/moodfabrics/api:v2
        imagePullPolicy: IfNotPresent
        name: chat-api
        ports:
        - containerPort: 3000
          protocol: TCP
