apiVersion: v1
kind: Service
metadata:
  name: chat-client
  namespace: default
  labels:
    app: chat-client
spec:
  ports:
    - portname: cleint-port
      port: 5008
      protocal: TCP
      targetport: 8080
  selector:
    app: chat-client
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: chat-client
  name: chat-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chat-client
    spec:
      containers:
      - env:
        - name: POSTGRES_CONNECTION_URI
          value: "postgres://postgres:password@postgres:5432/chat"      
        image: us.gcr.io/moodfabrics/chat-client:v2
        imagePullPolicy: IfNotPresent
        name: chat-client
        ports:
        - containerPort: 8080
          protocol: TCP
